1-3 Homeworks js advanced
alivka-oko/PurpleSchool-JS pull request #7
Opened 2024-09-15 13:51 UTC by alivka-oko

2024-09-17 20:41 UTC, Levitinn requested changes
есть комментарий по задаче с дайсом

2024-09-17 20:41 UTC, Levitinn commented on Js-advanced/2-dice/app.js
> +  const supportedTypes = ["D4", "D6", "D8", "D10", "D12", "D16", "D20"];
если использовать объект с ключами "D4", "D6", "D8" ..... задача станет куда проще

2024-09-20 06:29 UTC, alivka-oko commented on Js-advanced/2-dice/app.js
> +  const supportedTypes = ["D4", "D6", "D8", "D10", "D12", "D16", "D20"];
Доброе утро! Поправила на вариант решения через объект
Можете, пожалуйста, подробнее объяснить, почему решение с объектом считается проще в данном случае?

Что именно в использовании объекта делает задачу легче по сравнению с первым вариантом, где использовался массив и извлечение числового значения через substring?

2024-09-23 20:13 UTC, Levitinn approved these changes

2024-09-25 11:21 UTC, merged